/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(data)'}/maymoc` | `/maymoc`; params?: Router.UnknownInputParams; } | { pathname: `${'/(data)'}/maymoc/details` | `/maymoc/details`; params?: Router.UnknownInputParams; } | { pathname: `${'/(data)'}/maytinh/details` | `/maytinh/details`; params?: Router.UnknownInputParams; } | { pathname: `${'/(data)'}/maytinh` | `/maytinh`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dataClass)'}/details` | `/details`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dataClass)'}/list` | `/list`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/trangchu` | `/trangchu`; params?: Router.UnknownInputParams; } | { pathname: `${'/(menu)'}/taisan` | `/taisan`; params?: Router.UnknownInputParams; } | { pathname: `${'/(settings)'}/hoso` | `/hoso`; params?: Router.UnknownInputParams; } | { pathname: `${'/(settings)'}/thongtin` | `/thongtin`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(data)'}/maymoc` | `/maymoc`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(data)'}/maymoc/details` | `/maymoc/details`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(data)'}/maytinh/details` | `/maytinh/details`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(data)'}/maytinh` | `/maytinh`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(dataClass)'}/details` | `/details`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(dataClass)'}/list` | `/list`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(home)'}/trangchu` | `/trangchu`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(menu)'}/taisan` | `/taisan`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(settings)'}/hoso` | `/hoso`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(settings)'}/thongtin` | `/thongtin`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(data)'}/maymoc${`?${string}` | `#${string}` | ''}` | `/maymoc${`?${string}` | `#${string}` | ''}` | `${'/(data)'}/maymoc/details${`?${string}` | `#${string}` | ''}` | `/maymoc/details${`?${string}` | `#${string}` | ''}` | `${'/(data)'}/maytinh/details${`?${string}` | `#${string}` | ''}` | `/maytinh/details${`?${string}` | `#${string}` | ''}` | `${'/(data)'}/maytinh${`?${string}` | `#${string}` | ''}` | `/maytinh${`?${string}` | `#${string}` | ''}` | `${'/(dataClass)'}/details${`?${string}` | `#${string}` | ''}` | `/details${`?${string}` | `#${string}` | ''}` | `${'/(dataClass)'}/list${`?${string}` | `#${string}` | ''}` | `/list${`?${string}` | `#${string}` | ''}` | `${'/(home)'}/trangchu${`?${string}` | `#${string}` | ''}` | `/trangchu${`?${string}` | `#${string}` | ''}` | `${'/(menu)'}/taisan${`?${string}` | `#${string}` | ''}` | `/taisan${`?${string}` | `#${string}` | ''}` | `${'/(settings)'}/hoso${`?${string}` | `#${string}` | ''}` | `/hoso${`?${string}` | `#${string}` | ''}` | `${'/(settings)'}/thongtin${`?${string}` | `#${string}` | ''}` | `/thongtin${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(data)'}/maymoc` | `/maymoc`; params?: Router.UnknownInputParams; } | { pathname: `${'/(data)'}/maymoc/details` | `/maymoc/details`; params?: Router.UnknownInputParams; } | { pathname: `${'/(data)'}/maytinh/details` | `/maytinh/details`; params?: Router.UnknownInputParams; } | { pathname: `${'/(data)'}/maytinh` | `/maytinh`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dataClass)'}/details` | `/details`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dataClass)'}/list` | `/list`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/trangchu` | `/trangchu`; params?: Router.UnknownInputParams; } | { pathname: `${'/(menu)'}/taisan` | `/taisan`; params?: Router.UnknownInputParams; } | { pathname: `${'/(settings)'}/hoso` | `/hoso`; params?: Router.UnknownInputParams; } | { pathname: `${'/(settings)'}/thongtin` | `/thongtin`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
