/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(data)'}/maymoc` | `/maymoc`; params?: Router.UnknownInputParams; } | { pathname: `${'/(data)'}/maytinh` | `/maytinh`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/trangchu` | `/trangchu`; params?: Router.UnknownInputParams; } | { pathname: `${'/(menu)'}/taisan` | `/taisan`; params?: Router.UnknownInputParams; } | { pathname: `${'/(settings)'}/hoso` | `/hoso`; params?: Router.UnknownInputParams; } | { pathname: `${'/(settings)'}/thongtin` | `/thongtin`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `${'/(data)'}/maymoc/[id]` | `/maymoc/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(data)'}/maytinh/[id]` | `/maytinh/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(data)'}/maymoc` | `/maymoc`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(data)'}/maytinh` | `/maytinh`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(home)'}/trangchu` | `/trangchu`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(menu)'}/taisan` | `/taisan`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(settings)'}/hoso` | `/hoso`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(settings)'}/thongtin` | `/thongtin`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } } | { pathname: `${'/(data)'}/maymoc/[id]` | `/maymoc/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `${'/(data)'}/maytinh/[id]` | `/maytinh/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(data)'}/maymoc${`?${string}` | `#${string}` | ''}` | `/maymoc${`?${string}` | `#${string}` | ''}` | `${'/(data)'}/maytinh${`?${string}` | `#${string}` | ''}` | `/maytinh${`?${string}` | `#${string}` | ''}` | `${'/(home)'}/trangchu${`?${string}` | `#${string}` | ''}` | `/trangchu${`?${string}` | `#${string}` | ''}` | `${'/(menu)'}/taisan${`?${string}` | `#${string}` | ''}` | `/taisan${`?${string}` | `#${string}` | ''}` | `${'/(settings)'}/hoso${`?${string}` | `#${string}` | ''}` | `/hoso${`?${string}` | `#${string}` | ''}` | `${'/(settings)'}/thongtin${`?${string}` | `#${string}` | ''}` | `/thongtin${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(data)'}/maymoc` | `/maymoc`; params?: Router.UnknownInputParams; } | { pathname: `${'/(data)'}/maytinh` | `/maytinh`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/trangchu` | `/trangchu`; params?: Router.UnknownInputParams; } | { pathname: `${'/(menu)'}/taisan` | `/taisan`; params?: Router.UnknownInputParams; } | { pathname: `${'/(settings)'}/hoso` | `/hoso`; params?: Router.UnknownInputParams; } | { pathname: `${'/(settings)'}/thongtin` | `/thongtin`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | `/+not-found` | `${'/(data)'}/maymoc/${Router.SingleRoutePart<T>}` | `/maymoc/${Router.SingleRoutePart<T>}` | `${'/(data)'}/maytinh/${Router.SingleRoutePart<T>}` | `/maytinh/${Router.SingleRoutePart<T>}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `${'/(data)'}/maymoc/[id]` | `/maymoc/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(data)'}/maytinh/[id]` | `/maytinh/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
