/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(data)'}/taisan/details` | `/taisan/details`; params?: Router.UnknownInputParams; } | { pathname: `${'/(data)'}/taisan/list` | `/taisan/list`; params?: Router.UnknownInputParams; } | { pathname: `${'/(data)'}/taisan/related-list` | `/taisan/related-list`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dataClass)'}/details` | `/details`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dataClass)'}/list` | `/list`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/trangchu` | `/trangchu`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/settings/hoso` | `/settings/hoso`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/settings/thongtin` | `/settings/thongtin`; params?: Router.UnknownInputParams; } | { pathname: `${'/(menu)'}/taisan` | `/taisan`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(data)'}/taisan/details` | `/taisan/details`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(data)'}/taisan/list` | `/taisan/list`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(data)'}/taisan/related-list` | `/taisan/related-list`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(dataClass)'}/details` | `/details`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(dataClass)'}/list` | `/list`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(home)'}/trangchu` | `/trangchu`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(home)'}/settings/hoso` | `/settings/hoso`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(home)'}/settings/thongtin` | `/settings/thongtin`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(menu)'}/taisan` | `/taisan`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(data)'}/taisan/details${`?${string}` | `#${string}` | ''}` | `/taisan/details${`?${string}` | `#${string}` | ''}` | `${'/(data)'}/taisan/list${`?${string}` | `#${string}` | ''}` | `/taisan/list${`?${string}` | `#${string}` | ''}` | `${'/(data)'}/taisan/related-list${`?${string}` | `#${string}` | ''}` | `/taisan/related-list${`?${string}` | `#${string}` | ''}` | `${'/(dataClass)'}/details${`?${string}` | `#${string}` | ''}` | `/details${`?${string}` | `#${string}` | ''}` | `${'/(dataClass)'}/list${`?${string}` | `#${string}` | ''}` | `/list${`?${string}` | `#${string}` | ''}` | `${'/(home)'}/trangchu${`?${string}` | `#${string}` | ''}` | `/trangchu${`?${string}` | `#${string}` | ''}` | `${'/(home)'}/settings/hoso${`?${string}` | `#${string}` | ''}` | `/settings/hoso${`?${string}` | `#${string}` | ''}` | `${'/(home)'}/settings/thongtin${`?${string}` | `#${string}` | ''}` | `/settings/thongtin${`?${string}` | `#${string}` | ''}` | `${'/(menu)'}/taisan${`?${string}` | `#${string}` | ''}` | `/taisan${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(data)'}/taisan/details` | `/taisan/details`; params?: Router.UnknownInputParams; } | { pathname: `${'/(data)'}/taisan/list` | `/taisan/list`; params?: Router.UnknownInputParams; } | { pathname: `${'/(data)'}/taisan/related-list` | `/taisan/related-list`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dataClass)'}/details` | `/details`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dataClass)'}/list` | `/list`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/trangchu` | `/trangchu`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/settings/hoso` | `/settings/hoso`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/settings/thongtin` | `/settings/thongtin`; params?: Router.UnknownInputParams; } | { pathname: `${'/(menu)'}/taisan` | `/taisan`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
